cd /home/pi/RetroPie-Setup/tmp/build/
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/gcc-7_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/cpp-7_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/gcc-7-base_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6_2.28-10_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libgcc1_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/b/binutils/binutils_2.31.1-16_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libcc1-0_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libgcc-7-dev_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/i/isl/libisl19_0.20-2_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/m/mpfr4/libmpfr6_4.0.2-1_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libstdc++6_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/gcc-8-base_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libasan4-dbg_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libatomic1-dbg_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libcilkrts5-dbg_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/gcc-7-locales_7.4.0-6_all.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libubsan0-dbg_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libubsan0_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libgomp1-dbg_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libgomp1_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gmp/libgmp10_6.1.2+dfsg-4_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/m/mpclib3/libmpc3_1.1.0-1_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libasan4_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/b/binutils/binutils-arm-linux-gnueabihf_2.31.1-16_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/b/binutils/binutils-doc_2.31.1-16_all.deb
wget http://ftp.us.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.11.dfsg-1_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/b/binutils/libbinutils_2.31.1-16_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/b/binutils/binutils-common_2.31.1-16_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libatomic1_8.3.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-7/libcilkrts5_7.4.0-6_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/g/gcc-8/libgcc1-dbg_8.3.0-6_armhf.deb
sudo dpkg --auto-deconfigure -i *.deb
